.TH "batify" "1" "28 July 2020" "batify(1)" "User manual"

.SH NAME

batify \(em simple battery notification 

.SH SYNOPSIS

.PP
\fBbatify\fR [\fBOPTIONS\fR] [\fBBATTERY ID\fR]

.SH DESCRIPTION

.PP
\fBbatify\fR is simple battery notification. It reads information from sysfs and send notification (battery status, remaining percentage, remaining time) using libnotify. 

.SH OPTIONS

.IP "\fB-h\fR, \fB--help\fR" 5
Show help options
.IP "\fB-d\fR, \fB--debug\fR" 5
Enable debug information.
.IP "\fB-i\fR, \fB--interval\fR \fIinterval\fR" 5
Update interval in seconds. 
.br
Default: 5.
.IP "\fB-l\fR, \fB--low-level\fR \fIlow_level\fR" 5
Low battery level in percent. 
.br
Default: 20%.
.IP "\fB-c\fR, \fB--critical-level\fR \fIcritical_level\fR" 5
Critical battery level in percent. 
.br
Default: 10%.
.IP "\fB-f\fR, \fB--full-capacity\fR \fIfull_capacity\fR" 5
Full capacity for battery. 
.br
Default: 98%.

.SH EXAMPLES

.EX

.TP
batify 1
.TP
batify -i 10 1
.TP
batify -l 25 -c 15 -f 98 1
.EE


